### ISSUE TITLE
Handle click/drag/drop a point on the body?

### ISSUE THREAD

**Issue by namnm** [makehuman-js/makehuman-js#10]
This lib is awesome! I wonder if I can add text when click/drag/drop a point on the body, then attach that point to the body so when body move that point will move together?

**Comment by wassname** [comment]
Thanks!

You probably could, I'm using threejs for the 3D rendering, so it would be primarily threejs code. If you wanted to you could start with the example from https://threejs.org/examples/?q=drag that looks the closest. It would probably be a bit complex and take you at least a few day though.
