### ISSUE TITLE
How can I integrate makehuman npm models into react js

### ISSUE THREAD

**Issue by NaveenSelva-95** [makehuman-js/makehuman-js#16]
I am installed the npm makehuman js model but i dont have a reference to integrate it with my reactjs code. How can i call that model in my react code

**Comment by wassname** [comment]
There is no reference for using this with react. Makehuman-js uses the threejs webgl renderer (not the DOM). This would make proper integration with react challenging (although you can search "webgl react" to see examples). I'm afraid I can't help however. If you do integrate it, please share the result.
