### ISSUE TITLE
open example in android people model is black?

### ISSUE THREAD

**Issue by hillday** [makehuman-js/makehuman-js#5]
what's  the possible reason of makehuman example open in android system(android 6.x) ,the people model is show black?
![hp](https://user-images.githubusercontent.com/5390297/34904740-2986c60c-f887-11e7-981f-003fd79d0482.jpg)

**Comment by wassname** [comment]
Possibly the texture's aren't loading. Or perhaps it's a rendering error. I reckon you should look in a javascript debugger to see the errors.

**Comment by hillday** [comment]
Thanks for you reply.I found the reason is android is not surrport MeshPhongMaterial.

**Comment by wassname** [comment]
Good to know!
