### ISSUE TITLE
Question | Can I make my own pose using Javascript ?

### ISSUE THREAD

**Issue by Rutulpatel7077** [makehuman-js/makehuman-js#9]
Can I control body parts using JS?

**Comment by wassname** [comment]
Yeah you can, using position and pose. 

This project uses threejs for visualisation for docs [like this](https://threejs.org/docs/#api/en/objects/Skeleton) are relevent for setting the pose. 

To try it out, go to the [example](http://makehuman-js-example.wassname.com/) and in the javascript console execute `app.human.position.z -= 10` will make the model further way. Execute `app.human.skeleton.bones[2].quaternion.x-=0.3` to bend the models spine backwards like she's doing the limbo.

**Comment by wassname** [comment]
No documentation, this is a pretty new project that's been used by less than a dozen people. your best option is to check out the threejs docs I linked or google "Three.js Skeletal Animation" or similar.
